/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CardapioJpaController;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cardapio;

/**
 *
 * @author elias
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
   CardapioJpaController daoCardapio;
    /**
     * Creates new form TelaCardapio
     */
    public Interface() {
        initComponents();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("RestaurantePU");
        daoCardapio = new CardapioJpaController(emf);
        atualizaTabela();
    }
    
    public void atualizaTabela() {
        List<Cardapio> lista = this.daoCardapio.findAll();
        DefaultTableModel tabela = (DefaultTableModel) Tabela.getModel();
        tabela.setRowCount(0);
      
        
        for (Cardapio c: lista) {
            Object[] obj = new Object[] {
                c.getIdcardapio(), 
                c.getDia(), c.getPratoproteico(),  c.getOvolactovegetariano(), c.getGuarnicao(), c.getSaladas(),
                c.getSuco(), c.getSobremesa()
            };
            tabela.addRow(obj);
          
        }
    }
     public void preencheDado() {
        int linhaSelecionada = Tabela.getSelectedRow();
        
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        else {
            int codigo = Integer.parseInt(Tabela.getValueAt(linhaSelecionada, 0).toString());
            Cardapio c = this.daoCardapio.find(codigo);
            jTextSalada.setText(c.getSaladas());
            jTextVegetariano.setText(c.getOvolactovegetariano());
            jTextPrato.setText(c.getPratoproteico());
            jTextSobremesa.setText(c.getSobremesa());
            jTextGuarnicao.setText(c.getGuarnicao());
            jTextSuco.setText(c.getSuco());
            
            // Atualize os botÃµes dos dias da semana
            switch (c.getDia()) {
                case "SEG" -> jToggleseg.setSelected(true);
                case "TER" -> jToggleter.setSelected(true);
                case "QUA" -> jTogglequa.setSelected(true);
                case "QUI" -> jTogglequi.setSelected(true);
                case "SEX" -> jTogglesex.setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelGuarnicao = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextSobremesa = new javax.swing.JTextField();
        jLabelVegetariano = new javax.swing.JLabel();
        jLabelSaladas = new javax.swing.JLabel();
        jLabelSuco = new javax.swing.JLabel();
        jLabelPrato = new javax.swing.JLabel();
        jLabelSobremesa = new javax.swing.JLabel();
        jTextSalada = new javax.swing.JTextField();
        jTextGuarnicao = new javax.swing.JTextField();
        jTextSuco = new javax.swing.JTextField();
        jTextVegetariano = new javax.swing.JTextField();
        jTextPrato = new javax.swing.JTextField();
        jToggleseg = new javax.swing.JToggleButton();
        jTogglesex = new javax.swing.JToggleButton();
        jToggleter = new javax.swing.JToggleButton();
        jTogglequa = new javax.swing.JToggleButton();
        jTogglequi = new javax.swing.JToggleButton();
        jButtoneditar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jButtonexclui = new javax.swing.JButton();
        jButtonsalvar = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelGuarnicao.setText("Guarnicão");

        jLabel5.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 36)); // NOI18N
        jLabel5.setText("Restaurante Universitario");

        jTextSobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSobremesaActionPerformed(evt);
            }
        });

        jLabelVegetariano.setText("Ovolactovegetariano");

        jLabelSaladas.setText("Saladas");

        jLabelSuco.setText("Suco");

        jLabelPrato.setText("Prato Proteico");

        jLabelSobremesa.setText("Sobremesa");

        jTextSalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSaladaActionPerformed(evt);
            }
        });

        jTextGuarnicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGuarnicaoActionPerformed(evt);
            }
        });

        jTextSuco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSucoActionPerformed(evt);
            }
        });

        jTextVegetariano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVegetarianoActionPerformed(evt);
            }
        });

        jTextPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPratoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleseg);
        jToggleseg.setText("seg");
        jToggleseg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTogglesegActionPerformed(evt);
            }
        });

        buttonGroup1.add(jTogglesex);
        jTogglesex.setText("sex");
        jTogglesex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTogglesexActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleter);
        jToggleter.setText("ter");
        jToggleter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleterActionPerformed(evt);
            }
        });

        buttonGroup1.add(jTogglequa);
        jTogglequa.setText("qua");
        jTogglequa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTogglequaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jTogglequi);
        jTogglequi.setText("qui");
        jTogglequi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTogglequiActionPerformed(evt);
            }
        });

        jButtoneditar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtoneditar.setText("Editar");
        jButtoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneditarActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Dia", "Prato Proteico", "Ovolactovegetariano", "Guarnição", "Saladas", "suco", "Sobremesa"
            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        Tabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setMinWidth(0);
            Tabela.getColumnModel().getColumn(0).setPreferredWidth(0);
            Tabela.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jButtonexclui.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonexclui.setText("Excluir");
        jButtonexclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexcluiActionPerformed(evt);
            }
        });

        jButtonsalvar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonsalvar.setText("salvar");
        jButtonsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jToggleseg, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jToggleter, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jTogglequa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTogglequi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelVegetariano, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextVegetariano, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelSaladas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelGuarnicao, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelSuco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextSalada, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextGuarnicao, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextSuco, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jTextSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtoneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTogglesex, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonexclui, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTogglesex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleseg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTogglequa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTogglequi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextVegetariano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVegetariano, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGuarnicao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextGuarnicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSaladas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextSalada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtoneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextSuco, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSuco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButtonexclui, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String dia;
         
            
    private void jTextSobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSobremesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSobremesaActionPerformed

    private void jTextSaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSaladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSaladaActionPerformed

    private void jTextGuarnicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGuarnicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGuarnicaoActionPerformed

    private void jTextSucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSucoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSucoActionPerformed

    private void jTextVegetarianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVegetarianoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVegetarianoActionPerformed

    private void jTextPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPratoActionPerformed

    private void jTogglesegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTogglesegActionPerformed
         if (jToggleseg.isSelected()) {
                    buttonGroup1.clearSelection();
                    jToggleseg.setSelected(true);
                    dia = "seg";
                }         
    }//GEN-LAST:event_jTogglesegActionPerformed

    private void jButtoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneditarActionPerformed

        Cardapio cardapio = new Cardapio();
        cardapio.setDia(dia);
        cardapio.setSaladas(jTextSalada.getText());
        cardapio.setPratoproteico(jTextPrato.getText());
        cardapio.setOvolactovegetariano(jTextVegetariano.getText());
        cardapio.setGuarnicao(jTextGuarnicao.getText());
        cardapio.setSuco(jTextSuco.getText());
          cardapio.setSobremesa(jTextSobremesa.getText());
        try {
            this.daoCardapio.create(cardapio);
            JOptionPane.showMessageDialog(null, "Cardapio criado.");
            atualizaTabela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro" + e.getMessage());
        }
//      
    }//GEN-LAST:event_jButtoneditarActionPerformed

    private void jTogglesexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTogglesexActionPerformed
         if (jTogglesex.isSelected()) {
                    buttonGroup1.clearSelection();
                    jTogglesex.setSelected(true);
                    dia = "sex";
                } // TODO add your handling code here:
    }//GEN-LAST:event_jTogglesexActionPerformed

    private void jToggleterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleterActionPerformed
        if (jToggleter.isSelected()) {
                    buttonGroup1.clearSelection();
                    jToggleter.setSelected(true);
                    dia = "ter";
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleterActionPerformed

    private void jTogglequaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTogglequaActionPerformed
              if (jToggleter.isSelected()) {
                    buttonGroup1.clearSelection();
                    jTogglequa.setSelected(true);
                    dia = "ter";
                }         // TODO add your handling code here:
    }//GEN-LAST:event_jTogglequaActionPerformed

    private void jTogglequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTogglequiActionPerformed
        if (jTogglequi.isSelected()) {
                    buttonGroup1.clearSelection();
                    jTogglequi.setSelected(true);
                    dia = "qui";
                }      
    }//GEN-LAST:event_jTogglequiActionPerformed

    private void jButtonexcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexcluiActionPerformed
       int linhaSelecionada = Tabela.getSelectedRow();

        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar");
            return;
        }
        
        int codigo = Integer.parseInt(Tabela.getValueAt(linhaSelecionada, 0).toString());
        Cardapio c = this.daoCardapio.find(codigo);
        
        try {
            int i = JOptionPane.showConfirmDialog(null, "Deseja excluir essa cadastro?", "Excluir CLiente", JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_OPTION) {
                this.daoCardapio.remove(c);
                JOptionPane.showMessageDialog(null, "Cadastro removido");
                atualizaTabela();
            }
            else {
                JOptionPane.showMessageDialog(null, "Operação Cancelada");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro" + e.getMessage());
        }
                     

    }//GEN-LAST:event_jButtonexcluiActionPerformed

    private void jButtonsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalvarActionPerformed
        Cardapio cardapio = new Cardapio();
        cardapio.setDia(dia);
        cardapio.setSaladas(jTextSalada.getText());
        cardapio.setPratoproteico(jTextPrato.getText());
        cardapio.setOvolactovegetariano(jTextVegetariano.getText());
        cardapio.setGuarnicao(jTextGuarnicao.getText());
        cardapio.setSuco(jTextSuco.getText());     
        cardapio.setSobremesa(jTextSobremesa.getText());
        
        try {
            this.daoCardapio.create(cardapio);
            JOptionPane.showMessageDialog(null, "Cardapio criado.");
            atualizaTabela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro" + e.getMessage());
        }                

    }//GEN-LAST:event_jButtonsalvarActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        preencheDado();
    }//GEN-LAST:event_TabelaMouseClicked

    private void TabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaKeyReleased
        preencheDado();
    }//GEN-LAST:event_TabelaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtoneditar;
    private javax.swing.JButton jButtonexclui;
    private javax.swing.JButton jButtonsalvar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelGuarnicao;
    private javax.swing.JLabel jLabelPrato;
    private javax.swing.JLabel jLabelSaladas;
    private javax.swing.JLabel jLabelSobremesa;
    private javax.swing.JLabel jLabelSuco;
    private javax.swing.JLabel jLabelVegetariano;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextGuarnicao;
    private javax.swing.JTextField jTextPrato;
    private javax.swing.JTextField jTextSalada;
    private javax.swing.JTextField jTextSobremesa;
    private javax.swing.JTextField jTextSuco;
    private javax.swing.JTextField jTextVegetariano;
    private javax.swing.JToggleButton jTogglequa;
    private javax.swing.JToggleButton jTogglequi;
    private javax.swing.JToggleButton jToggleseg;
    private javax.swing.JToggleButton jTogglesex;
    private javax.swing.JToggleButton jToggleter;
    // End of variables declaration//GEN-END:variables
}
